name: Generate Index Page

on:
  push:
    branches:
      - main   # 如果默认分支是 master，请改成 master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate index.html
        run: |
          echo "<!DOCTYPE html>" > index.html
          echo "<html><head><meta charset='utf-8'><title>reading glasses</title></head><body>" >> index.html
          echo "<h1>reading glasses</h1><ul>" >> index.html

          # 用 NUL 分隔处理文件名中空格
          find . -type f -name "*.html" ! -name "index.html" -print0 | while IFS= read -r -d '' file; do
            file="${file#./}"                     # 去掉开头的 ./
            name=$(echo "$file" | sed 's/\.html$//')   # 去掉 .html 后缀
            echo "<li><a href=\"$file\">$name</a></li>" >> index.html
          done

          echo "</ul></body></html>" >> index.html

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git diff --cached --quiet || git commit -m "Auto update index.html"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
