name: Generate Index & Random Internal Links Optimized

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate index and optimized internal links
        run: |
          # 收集所有 HTML 文件
          mapfile -d '' files < <(find . -type f -name "*.html" ! -name "index.html" -print0)

          # 生成 index.html（完整导航）
          echo "<!DOCTYPE html>" > index.html
          echo "<html><head><meta charset='utf-8'><title>reading glasses</title></head><body>" >> index.html
          echo "<h1>reading glasses</h1><ul>" >> index.html
          for file in "${files[@]}"; do
            file="${file#./}"
            name=$(echo "$file" | sed 's/\.html$//')
            echo "<li><a href=\"$file\">$name</a></li>" >> index.html
          done
          echo "</ul></body></html>" >> index.html

          # 每个 HTML 页面底部添加随机内部链接
          for file in "${files[@]}"; do
            file="${file#./}"

            # 移除已有 internal-links 区块，避免重复
            sed -i '/<!-- internal-links start -->/,/<!-- internal-links end -->/d' "$file"

            # 构建候选链接数组（排除自己）
            other_links=()
            for link in "${files[@]}"; do
              link="${link#./}"
              if [[ "$link" != "$file" ]]; then
                other_links+=("$link")
              fi
            done

            # 打乱顺序
            shuffled=($(shuf -e "${other_links[@]}"))

            # 取前 3-5 个随机链接
            count=$(shuf -i 3-5 -n 1)
            selected=("${shuffled[@]:0:$count}")

            # 写入 HTML
            echo "<!-- internal-links start -->" >> "$file"
            echo "<hr><h2>Other Pages</h2><ul>" >> "$file"
            for link in "${selected[@]}"; do
              name=$(echo "$link" | sed 's/\.html$//')
              echo "<li><a href=\"$link\">$name</a></li>" >> "$file"
            done
            echo "</ul><!-- internal-links end -->" >> "$file"
          done

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git add *.html
          git diff --cached --quiet || git commit -m "Auto update index.html and optimized internal links"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
